import { StyleSheet } from 'react-native';
import { ACCENT, ACCENT_LIGHT, commonStyles } from './common.styles';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: commonStyles.BG_PRIMARY,
  },
  inner: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  logoBox: {
    alignItems: 'center',
    marginBottom: 32,
  },
  logoIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  logoText: {
    fontSize: 32,
    fontWeight: '800',
    color: commonStyles.TEXT_PRIMARY,
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 13,
    color: commonStyles.TEXT_SECONDARY,
    textAlign: 'center',
    marginBottom: 40,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  instructionText: {
    fontSize: 13,
    color: commonStyles.TEXT_TERTIARY,
    textAlign: 'center',
    marginBottom: 28,
    letterSpacing: 0.5,
    fontWeight: '500',
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 12,
    color: commonStyles.TEXT_TERTIARY,
    letterSpacing: 1.5,
    marginBottom: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: commonStyles.BG_SECONDARY,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    fontSize: 16,
    color: commonStyles.TEXT_PRIMARY,
    borderWidth: 1.5,
    borderColor: commonStyles.BORDER_COLOR,
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: ACCENT,
    backgroundColor: commonStyles.BG_TERTIARY,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  button: {
    backgroundColor: ACCENT,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 32,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: commonStyles.BORDER_COLOR,
  },
  dividerText: {
    color: commonStyles.TEXT_MUTED,
    fontSize: 11,
    marginHorizontal: 16,
    letterSpacing: 2,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  secondaryButton: {
    borderWidth: 1.5,
    borderColor: commonStyles.BORDER_LIGHT,
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: 'transparent',
  },
  secondaryButtonText: {
    color: ACCENT_LIGHT,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});
