import { StyleSheet } from 'react-native';
import { ACCENT, commonStyles } from './common.styles';

export const foldersStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: commonStyles.BG_PRIMARY },
  center: { justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: commonStyles.BORDER_COLOR,
  },
  greeting: { fontSize: 12, color: commonStyles.TEXT_TERTIARY, letterSpacing: 1, fontWeight: '500', textTransform: 'uppercase' },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: commonStyles.TEXT_PRIMARY,
    marginTop: 6,
    letterSpacing: 2,
  },
  logoutBtn: {
    borderWidth: 1.5,
    borderColor: '#EF4444',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  logoutText: { color: '#EF4444', fontWeight: '700', fontSize: 12, letterSpacing: 1, textTransform: 'uppercase' },
  statsBar: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: commonStyles.BORDER_COLOR,
  },
  stat: { flex: 1, alignItems: 'center' },
  statNum: { fontSize: 24, fontWeight: '800', color: ACCENT },
  statLabel: { fontSize: 11, color: commonStyles.TEXT_TERTIARY, letterSpacing: 1.5, marginTop: 4, fontWeight: '600', textTransform: 'uppercase' },
  statDivider: { width: 1, backgroundColor: commonStyles.BORDER_COLOR },
  list: { paddingHorizontal: 20, paddingBottom: 100 },
  folderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: commonStyles.BG_SECONDARY,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: commonStyles.BORDER_COLOR,
    borderRadius: 12,
  },
  folderLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  folderDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 14,
    backgroundColor: ACCENT,
  },
  folderName: { fontSize: 16, fontWeight: '700', color: commonStyles.TEXT_PRIMARY },
  folderCount: { fontSize: 12, color: commonStyles.TEXT_TERTIARY, marginTop: 3, fontWeight: '500' },
  arrow: { fontSize: 18, color: commonStyles.TEXT_MUTED },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 30 },
  empty: { alignItems: 'center' },
  emptyIcon: { fontSize: 48, color: commonStyles.TEXT_MUTED, fontWeight: '200', marginBottom: 16 },
  emptyText: { fontSize: 18, color: commonStyles.TEXT_PRIMARY, fontWeight: '700', letterSpacing: 0.5 },
  emptySubtext: { fontSize: 13, color: commonStyles.TEXT_TERTIARY, marginTop: 10, letterSpacing: 0.3, textAlign: 'center' },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    width: 60,
    height: 60,
    backgroundColor: ACCENT,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  fabText: { fontSize: 26, color: '#FFF', fontWeight: '600', lineHeight: 30 },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  modalContent: {
    backgroundColor: commonStyles.BG_SECONDARY,
    padding: 24,
    borderWidth: 1,
    borderColor: commonStyles.BORDER_COLOR,
    borderRadius: 14,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: commonStyles.TEXT_PRIMARY,
    letterSpacing: 2,
    marginBottom: 20,
    textTransform: 'uppercase',
  },
  modalInput: {
    backgroundColor: commonStyles.BG_PRIMARY,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: commonStyles.TEXT_PRIMARY,
    borderWidth: 1.5,
    borderColor: commonStyles.BORDER_COLOR,
    marginBottom: 24,
    fontWeight: '500',
    borderRadius: 10,
  },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  modalCancel: { paddingVertical: 12, paddingHorizontal: 18 },
  modalCancelText: { color: commonStyles.TEXT_TERTIARY, fontSize: 13, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  modalCreate: {
    backgroundColor: ACCENT,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  modalCreateText: { color: '#FFF', fontSize: 13, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  buttonDisabled: { opacity: 0.6 },
});

export { ACCENT };
