import { StyleSheet } from 'react-native';
import { ACCENT, ACCENT_LIGHT, commonStyles } from './common.styles';

export const signupStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: commonStyles.BG_PRIMARY,
  },
  inner: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    color: commonStyles.TEXT_PRIMARY,
    marginBottom: 10,
    lineHeight: 42,
  },
  subtitle: {
    fontSize: 13,
    color: commonStyles.TEXT_SECONDARY,
    marginBottom: 36,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 12,
    color: commonStyles.TEXT_TERTIARY,
    letterSpacing: 1.5,
    marginBottom: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: commonStyles.BG_SECONDARY,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    fontSize: 16,
    color: commonStyles.TEXT_PRIMARY,
    borderWidth: 1.5,
    borderColor: commonStyles.BORDER_COLOR,
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: ACCENT,
    backgroundColor: commonStyles.BG_TERTIARY,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  button: {
    backgroundColor: ACCENT,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  backLink: {
    marginTop: 28,
    paddingVertical: 14,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: commonStyles.BORDER_COLOR,
  },
  backText: {
    color: ACCENT_LIGHT,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});
